---

- name: restart newrelic-infra
  service:
    name:  newrelic-infra
    listen: "restart ms-services"
    state: restarted

- name: restart php-8.1-fpm
  listen: "restart ms-services"
  service: name=php8.1-fpm state=restarted

