system:
  apt:
    repositories:
      - ppa:ondrej/php

php:
  versions:
    - version: 8.1
  projects:
    - path: /var/www/ms_secret_manager/
      framework: laravel

git:
  - repo: git@github.com:feed-manager-bdx/ms-secret-manager.git
    dest: /var/www/ms_secret_manager/
    version: master
    deploy_key: ms_secret_manager-rsa
    user: www-data
    group: www-data

apache:
  vhosts:
    - domain: sm1.api.snapfeat.com
      ip: 54.36.102.44
      dir: /var/www/ms_secret_manager/public/
      email: court@labelium.com
      phpversion: 81

certbot:
  email: court@labelium.com
  domain: sm1.api.snapfeat.com

newrelic:
  newrelic_license_key: eu01xxa8e36429479c60af21cf410bceFFFFNRAL
  newrelic_appname: MS Secret Manager
