- name: MS Secret Manager
  hosts: ms_secret_manager_prod
  user: ubuntu
  become: true
  become_user: root

  roles:
#    - roles/system/base
#    - roles/system/apache
#    - roles/system/phpfpm
#    - roles/system/certbot
#    - roles/system/newrelic
   - roles/app/git
   - role: roles/app/php
     become: yes
     become_user: www-data



